@host=https://localhost:5168

GET {{host}}/ListDinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5OWM1ODc4NC03NjU1LTQ5ZWQtOTEzNS1lNGY3NGRmNTY4MjEiLCJnaXZlbl9uYW1lIjoiSnVsacOhbiIsImZhbWlseV9uYW1lIjoiUG9kYmVyc2ljaCIsImp0aSI6IjgxNzZkYTc1LTk4YWItNDg3NC04ZDI5LTY5MzczNDhiMzcwMyIsImV4cCI6MTc3MDc1OTU2MywiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.qCqeC62G6km6Euy5ALIRFKLs4q1FPY1ETo7GDNJvzqUeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uVXNlcnMuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJKdWxpw6FuIiwiZmFtaWx5X25hbWUiOiJQb2RiZXJzaWNoIiwianRpIjoiNGQwY2MwZjMtY2IzMy00NmRjLThhMDAtOTAxNzAzMmZjYzM0IiwiZXhwIjoxNzcwOTE0MjcwLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.OEEg28zoM7Zoq_ACdGQ_YFnTkcZRCZ4QMv3krY-xBcI